services:
  kflaky:
    build: .
    container_name: kFlaky
    volumes:
      - ./run/default.db:/app/default.db
      - ./run/config_pairs.json:/app/config.json
      - ./run/logs:/app/logs
      - ./run/temp:/app/temp
      - /home/matthias/Documents/opensource/ormlite-core:/app/ormlite-alphabetical
      - /home/matthias/Documents/opensource/ormlite-core-reverse:/app/ormlite-reverse
    deploy:
      resources:
        limits:
          memory: 8GB
