services:
  kflaky:
    build: .
    container_name: kFlaky
    volumes:
      - ./run/default.db:/app/default.db
      - ./run/docker/maven-config.json:/app/config.json
      - ./run/logs:/app/logs
      - ./run/temp:/app/temp
    deploy:
      resources:
        limits:
          memory: 8GB
