name: Publish Jar files

on:
  release:
    types: [published]

jobs:
  buildJava8:
    name: Build java 8 jar file
    runs-on: ubuntu-latest
    env:
      JVM_VERSION: 8
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
      - name: Build with Gradle Wrapper
        run: ./gradlew build
      - name: Upload jar to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/libs/kFlaky-0.2.jar
          asset_name: jdk8-kFlaky.jar
          tag: ${{ github.ref }}
  buildJava21:
    name: Build java 21 jar file
    runs-on: ubuntu-latest
    env:
      JVM_VERSION: 21
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
      - name: Build with Gradle Wrapper
        run: ./gradlew build
      - name: Upload jar to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/libs/kFlaky-0.2.jar
          asset_name: jdk21-kFlaky.jar
          tag: ${{ github.ref }}
  buildJava11:
    name: Build java 11 jar file
    runs-on: ubuntu-latest
    env:
      JVM_VERSION: 11
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
      - name: Build with Gradle Wrapper
        run: ./gradlew build
      - name: Upload jar to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/libs/kFlaky-0.2.jar
          asset_name: jdk11-kFlaky.jar
          tag: ${{ github.ref }}
